name: Black Code Formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      # Check out your code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python (Black needs Python)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install Black
      - name: Install Black
        run: pip install black

      # Format all Python files in the repo
      - name: Run Black
        run: black .

      # Commit & push back any changes (only on push, not on PR from fork)
      - name: Commit formatted code
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "style: auto-format Python code with Black"
            git push
          fi
