[server]
fileWatcherType = "none"
port = 8501
maxUploadSize = 5000  # 5000 MB

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[logger]
level = "info"

[global]
developmentMode = false

